[package]
name = "embedded-encoder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
postcard = "1.1.3"
serde = { version = "1.0.*", features = ["derive"] }
